### ISSUE TITLE
Default formatter scripts don't work when run from source directory

### ISSUE THREAD

**Issue by micsthepick** [obsproject/obs-plugintemplate#121]
### Operating System Info

Ubuntu 22.04

### OBS Studio Version

30.1.2

### OBS Studio Log URL

N/A

### Expected Behavior

runs from the CWD or runs from src dir automatically

### Current Behavior

expects to run from project_root (up a level from src)

### Steps to Reproduce

1. clone this repo
2. change formatting of a c/c++ module
3. cd src
4. ../build-aux/run-clang-format
...

### Anything else we should know?

I'm using the template to include a sub-project, and I can imagine a use case where someone includes a sub-repository not working well with the current clang-format script. It also seems very temperamental - it must be used exactly in one way.

**Comment by PatTheMav** [comment]
That's intentional - it's designed to be run from the checkout directory by the GHA actions provided by the template and is only made available for convenience outside of that. 

Any other use-case can and should be fulfilled by running the formatters directly (e.g. via a pre-commit hook) or using an IDE with appropriate formatting support.
