### ISSUE TITLE
Windows package does not have DLLs

### ISSUE THREAD

**Issue by norihiro** [obsproject/obs-plugintemplate#2]
## Platform

Windows build (32bit and 64bit) on Azure Pipeline
Operating system and version:
OBS Studio version:

## Expected Behavior
packaged ZIP file contains DLL files

## Current Behavior
The ZIP file contains only two file as below.
Zip file size: 396710 bytes, number of entries: 3
```
drwx---     6.3 fat        0 bx stor 20-Jun-27 11:51 obs-plugins/
-rw-a--     6.3 fat   913408 bx defN 20-Jun-27 11:51 obs-plugins/32bit
-rw-a--     6.3 fat   856064 bx defN 20-Jun-27 11:51 obs-plugins/64bit
```
The files `32bit` and `64bit` are not directories but looks like PDB files.

## Steps to Reproduce

I think buiid_config would be relevant to this issue.
```
build_config: RelWithDebInfo
```
1. I copied files from obs-plugintemplate to my project (named `obs-vnc`), and modified something.
2. Build it on azure-pipeline. You can find my build log [here](https://dev.azure.com/norihiro0169/obs-vnc/_build/results?buildId=127&view=results). The status is success.
3. After building a plugin, I use `zipinfo` to look into the contents. The result is as below.
```
 zipinfo ../azure/obs-vnc/windows_build/obs-vnc-9330329-Windows.zip 
Archive:  ../azure/obs-vnc/windows_build/obs-vnc-9330329-Windows.zip
Zip file size: 396710 bytes, number of entries: 3
drwx---     6.3 fat        0 bx stor 20-Jun-27 11:51 obs-plugins/
-rw-a--     6.3 fat   913408 bx defN 20-Jun-27 11:51 obs-plugins/32bit
-rw-a--     6.3 fat   856064 bx defN 20-Jun-27 11:51 obs-plugins/64bit
3 files, 1769472 bytes uncompressed, 396260 bytes compressed:  77.6%
```

## Additional information

Maybe `OR` that are used at `command add_custom_command` in `CMakeLists.txt` does not work.
I removed `if` condition to execute the command all the time, then the ZIP file contains the DLL files.

**Comment by camblomquist** [comment]
In the post_build for Windows, we see the following:
```
COMMAND if $<CONFIG:Debug>==1 (
	"${CMAKE_COMMAND}" -E copy
		"$<TARGET_FILE:${CMAKE_PROJECT_NAME}>"
		"${LIBOBS_INCLUDE_DIR}/../${OBS_BUILDDIR_ARCH}/rundir/$<CONFIG>/obs-plugins/${ARCH_NAME}"
)

COMMAND if $<CONFIG:Debug>==1 (
	"${CMAKE_COMMAND}" -E copy
		"$<TARGET_PDB_FILE:${CMAKE_PROJECT_NAME}>"
		"${LIBOBS_INCLUDE_DIR}/../${OBS_BUILDDIR_ARCH}/rundir/$<CONFIG>/obs-plugins/${ARCH_NAME}"
)
```
Looking at the documentation for CMake, we see that `-E copy` will copy the source file(s) to the destination, either in the given directory, or *as the given file name* if the directory does not exist.
It's a double whammy of unfortunate circumstances. The template is expecting the architecture suffix for the obs-studio build directory even though it's not required. If you used `build` instead of `build64`, then it will create an empty build64, an empty rundir, an empty ${CONFIG}, and an empty obs-plugins.
Then, because 64bit doesn't exist as a folder, we see it copy the DLL and name it `64bit`, then it copies the PDB and names it `64bit`, replacing the copied DLL.

I know this issue is over a month old now and you've probably resolved the issue yourself, but I thought it was still worth digging into because I encountered the same issue.

Either the template needs to specify this requirement (among others,) or CMakeLists.txt needs to be updated to be more agnostic about which build directory is used.

**Comment by norihiro** [comment]
I found that `OR` statements as below are not working.
```
        COMMAND if $<CONFIG:Release>==1 OR $<CONFIG:RelWithDebInfo>==1 (
            "${CMAKE_COMMAND}" -E make_directory
                "${RELEASE_DIR}/data/obs-plugins/${CMAKE_PROJECT_NAME}"
                "${RELEASE_DIR}/obs-plugins/${ARCH_NAME}"
        )

        COMMAND if $<CONFIG:Release>==1 OR $<CONFIG:RelWithDebInfo>==1 (
            "${CMAKE_COMMAND}" -E copy_directory
                "${PROJECT_SOURCE_DIR}/data"
                "${RELEASE_DIR}/data/obs-plugins/${CMAKE_PROJECT_NAME}"
        )

        COMMAND if $<CONFIG:Release>==1 OR $<CONFIG:RelWithDebInfo>==1 (
            "${CMAKE_COMMAND}" -E copy
                "$<TARGET_FILE:${CMAKE_PROJECT_NAME}>"
                "${RELEASE_DIR}/obs-plugins/${ARCH_NAME}"
        )
```

I changed them to run without `if` statements as a workaround.
```
        COMMAND "${CMAKE_COMMAND}" -E make_directory "${RELEASE_DIR}/data/obs-plugins/${CMAKE_PROJECT_NAME}" "${RELEASE_DIR}/obs-plugins/${ARCH_NAME}"
        COMMAND "${CMAKE_COMMAND}" -E copy_directory "${PROJECT_SOURCE_DIR}/data" "${RELEASE_DIR}/data/obs-plugins/${CMAKE_PROJECT_NAME}"
        COMMAND "${CMAKE_COMMAND}" -E copy "$<TARGET_FILE:${CMAKE_PROJECT_NAME}>" "${RELEASE_DIR}/obs-plugins/${ARCH_NAME}/"
```

**Comment by Palakis** [comment]
Thanks @norihiro and @camblomquist. I was able to reproduce and fix this issue.
