### ISSUE TITLE
Missing util/threading.h on mac and enum OBS_TEXT_INFO on ubuntu

### ISSUE THREAD

**Issue by CodeYan01** [obsproject/obs-plugintemplate#79]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

29.1.2

### OBS Studio Log URL

N/A

### Expected Behavior

I tried to update my plugin with the new plugin template changes. But i get these errors that don't make sense for me (cause windows works)
https://github.com/CodeYan01/media-playlist-source/actions/runs/5431829190/jobs/9878449528

### Current Behavior

Please check github action run

### Steps to Reproduce

1. Applied the new CMake changes
2. Push
...

**Comment by gxalpha** [comment]
`enum OBS_TEXT_INFO` missing on Ubuntu is because we use the system provided package to build against, which is ancient (27.2).
We'd either need to use a version that's compiled on GitHub Actions before the plugin similarly to Windows or macOS (which might be what was done before the rework?), or provide a recent libobs-dev from the PPA, or you'd need to ifdef the INFO text to not be compiled on that system.
Which OBS version to compile against on Ubuntu is a difficult question to answer, as anyone who just does `apt install obs-studio` without adding our PPA first will have that old OBS version where the plugin then wouldn't work if compiled against a newer OBS. Alternatively if we use the default version (like it is being done now), "new" APIs etc won't be available, either holding the plugin back or causing authors to just not distribute them on Ubuntu (the latter is what I plan to be doing for my plugins).

**Comment by gxalpha** [comment]
As a note here, this is the export list: 

https://github.com/obsproject/obs-studio/blob/e8602897d72d6acdd0e4c3809a5dcbf660e78dd6/libobs/CMakeLists.txt#L261-L326

It probably needs going over to see which headers (like the one missing here on macOS) need exporting as well.

**Comment by gxalpha** [comment]
@CodeYan01 @miaulightouch (from #80), please try current if master fixes Ubuntu for you.
macOS fix would probably be obs-studio side and is still pending, see the comment above.

**Comment by CodeYan01** [comment]
Ubuntu build worked successfully on mine, thank you

**Comment by miaulightouch** [comment]
yes, Ubuntu build works.

https://github.com/miaulightouch/obs-test-plugin/actions/runs/5503849230
